name: Format

on:
  push:
    branches:

jobs:
  format:
    name: Prettier
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run format
        run: bun run format

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format by GitHub Actions
