name: Format

on:
  push:
    branches:

jobs:
  format:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run format
        run: yarn format

      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Format by GitHub Actions
