name: Lint

on:
  push:
    branches:

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - name: Run lint
        run: bun run lint
